package samples.com.cruumb.samples.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import samples.com.cruumb.samples.greendao.db.HogeTable;

import samples.com.cruumb.samples.greendao.db.HogeTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hogeTableDaoConfig;

    private final HogeTableDao hogeTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hogeTableDaoConfig = daoConfigMap.get(HogeTableDao.class).clone();
        hogeTableDaoConfig.initIdentityScope(type);

        hogeTableDao = new HogeTableDao(hogeTableDaoConfig, this);

        registerDao(HogeTable.class, hogeTableDao);
    }
    
    public void clear() {
        hogeTableDaoConfig.getIdentityScope().clear();
    }

    public HogeTableDao getHogeTableDao() {
        return hogeTableDao;
    }

}
