package samples.com.cruumb.samples.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOGE_TABLE.
 */
public class HogeTable {

    private long id;
    private long fuga;
    /** Not-null value. */
    private String hoge;

    public HogeTable() {
    }

    public HogeTable(long id) {
        this.id = id;
    }

    public HogeTable(long id, long fuga, String hoge) {
        this.id = id;
        this.fuga = fuga;
        this.hoge = hoge;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getFuga() {
        return fuga;
    }

    public void setFuga(long fuga) {
        this.fuga = fuga;
    }

    /** Not-null value. */
    public String getHoge() {
        return hoge;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHoge(String hoge) {
        this.hoge = hoge;
    }

}
