package samples.com.cruumb.samples.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import samples.com.cruumb.samples.greendao.db.HogeTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table HOGE_TABLE.
*/
public class HogeTableDao extends AbstractDao<HogeTable, Long> {

    public static final String TABLENAME = "HOGE_TABLE";

    /**
     * Properties of entity HogeTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "ID");
        public final static Property Fuga = new Property(1, long.class, "fuga", false, "FUGA");
        public final static Property Hoge = new Property(2, String.class, "hoge", false, "HOGE");
    };


    public HogeTableDao(DaoConfig config) {
        super(config);
    }
    
    public HogeTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'HOGE_TABLE' (" + //
                "'ID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE ," + // 0: id
                "'FUGA' INTEGER NOT NULL ," + // 1: fuga
                "'HOGE' TEXT NOT NULL );"); // 2: hoge
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'HOGE_TABLE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HogeTable entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getFuga());
        stmt.bindString(3, entity.getHoge());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HogeTable readEntity(Cursor cursor, int offset) {
        HogeTable entity = new HogeTable( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // fuga
            cursor.getString(offset + 2) // hoge
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HogeTable entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setFuga(cursor.getLong(offset + 1));
        entity.setHoge(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HogeTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HogeTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
